name: manually build package using xcpkg

on:
  workflow_dispatch:
    inputs:

      package-name:
        description: input the package name to be built
        required: true

      target-platform:
        description: input a target platform to be built for
        type: choice
        options:
          - MacOSX
          - AppleTVOS
          - AppleTVSimulator
          - WatchOS
          - WatchSimulator
          - iPhoneOS
          - iPhoneSimulator

      target-version:
        description: input a min target platform version to be
supported
        required: true

      target-arch:
        description: choose a target arch to be built for
        type: choice
        options:
          - x86_64
          - arm64
          - arm64e
          - arm64_32
          - armv7k

      profile:
        description: choose a build profile
        type: choice
        options:
          - release
          - debug

      log-level:
        description: choose a log-level
        type: choice
        options:
          - ''
          - '-q'
          - '-v'
          - '-vv'

jobs:

  prepare:
    runs-on: ubuntu-latest

    steps:
      - id:  prepare
        run: |
          if [ ${{ github.event.inputs.target-arch }} = x86_64 ] ;
then
              printf 'RUNS_ON=macos-13\n' >> "$GITHUB_OUTPUT"
          else
              printf 'RUNS_ON=macos-14\n' >> "$GITHUB_OUTPUT"
          fi

    outputs:
      runs-on: ${{ steps.prepare.outputs.RUNS_ON }}


  build:
    needs: prepare

    runs-on: ${{ needs.prepare.outputs.runs-on }}

    steps:
      - run: export -p

      - run: curl -LO
https://raw.githubusercontent.com/leleliu008/xcpkg/master/xcpkg
      - run: chmod a+x xcpkg
      - run: ./xcpkg formula-repo-add jakemanger
https://github.com/jakemanger/xcpkg-formula-repository-official-core
      - run: ./xcpkg setup
      - run: ./xcpkg update

      - run: ./xcpkg install ${{ github.event.inputs.log-level }}
${{ github.event.inputs.target-platform }}-${{
github.event.inputs.target-version }}-${{
github.event.inputs.target-arch }}/${{
github.event.inputs.package-name }} --profile=${{
github.event.inputs.profile }}

      - run: ./xcpkg pack    ${{ github.event.inputs.log-level }}
${{ github.event.inputs.target-platform }}-${{
github.event.inputs.target-version }}-${{
github.event.inputs.target-arch }}/${{
github.event.inputs.package-name }} -t tar.xz -o .

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.package-name }}-${{
github.event.inputs.target-platform }}-${{
github.event.inputs.target-version }}-${{
github.event.inputs.target-arch }}-${{ github.event.inputs.profile
}}
          path: ./*.tar.xz
